fix: hide private user data in api/v3/users/[uid]
NodeBB/NodeBB pull request #9621
Opened 2021-06-21 17:02 UTC by gasoved

2021-06-23 18:04 UTC, julianlam requested changes
It would be good if the data removal logic from within `helpers.getUserDataByUserSlug` used the new `user.hidePrivateData` as well, so as to maintain DRY, what do you think?

2021-06-23 18:04 UTC, julianlam commented on src/user/data.js
> +		return _userData;
Missing removal of `ips` and `moderationNote` from this method (if this method is used in `getUserDataByUserSlug`, which I think it should

2021-06-30 13:38 UTC, gasoved commented
I thought it's a good enough place to not follow DRY. Use case is a bit different, and it would cause extra DB calls for both endpoints.

I'm pushing a commit doing that nevertheless. I'm in favor of the first version.
(This also adds two possible fields to /api/v3/users/:uid endpoint.)

2021-06-30 21:02 UTC, julianlam commented
Merged via 97c8569a798075c50e93e585ac741ab55cb7c28b

2021-06-30 21:02 UTC, closed without merging